dating:
  match-cooldown: 3

ml:
  knn:
    path-to-script: src\main\java\ru\sirius\concordia\match\ml\KNN\ml.py
    path-to-users-csv: src\main\java\ru\sirius\concordia\match\ml\KNN\output.csv
    schedule-generate-user-tags-csv: 0 0/10 * * * ?

photo:
  storage:
    path: uploads/users

security:
  auth:
    user:
      jwt:
        secret-key: qwerty123456

server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  port: ${PORT:8080}
  error:
    include-message: always
  forward-headers-strategy: FRAMEWORK

spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
    mongodb:
      username: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      password: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      host: ${ME_CONFIG_MONGODB_HOST}
      port: ${ME_CONFIG_MONGODB_PORT}
      database: ${ME_CONFIG_MONGODB_DATABASE}
      authentication-database: ${ME_CONFIG_MONGODB_AUTHENTICATION_DATABASE}
  jmx:
    enabled: false
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  flyway:
    out-of-order: true
  threads:
    virtual:
      enabled: true


application:
  web:
    cors:
      allowed-origins:
        - "http://127.0.0.1:5173"
        - "http://127.0.0.1:27017"
        - "http://127.0.0.1:8081"
        - "http://127.0.0.1:5174"
        - "http://localhost"
        - "http://localhost:8000"
  version: "1.0.0"